
DROP TABLE IF EXISTS TB_TELEFONE;
DROP TABLE IF EXISTS TB_ENDERECO;
DROP TABLE IF EXISTS TB_FUNCIONARIO;
DROP TABLE IF EXISTS TB_TIPO_LOGRADOURO;
DROP TABLE IF EXISTS TB_TIPO_ENDERECO;
DROP TABLE IF EXISTS TB_CARGO;
DROP TABLE IF EXISTS TB_DEPARTAMENTO;
DROP TABLE IF EXISTS TB_CIDADE;
DROP TABLE IF EXISTS TB_ESTADO;
DROP TABLE IF EXISTS TB_REGIAO;
DROP TABLE IF EXISTS TB_TIPO_TELEFONE;


/*

TIPO LOGRADOURO

*/

CREATE TABLE IF NOT EXISTS TB_TIPO_LOGRADOURO(
  codigo LONG AUTO_INCREMENT  PRIMARY KEY,
  descricao VARCHAR(250) NOT NULL
 );



/*

TIPO ENDERECO

*/

CREATE TABLE IF NOT EXISTS TB_TIPO_ENDERECO (
  codigo LONG AUTO_INCREMENT  PRIMARY KEY,
  descricao VARCHAR(250) NOT NULL
 );





/*

DEPARTAMENTO

*/

CREATE TABLE IF NOT EXISTS TB_DEPARTAMENTO (
  codigo LONG AUTO_INCREMENT  PRIMARY KEY,
  descricao VARCHAR(250) NOT NULL
 );


/*

CARGO

*/


CREATE TABLE IF NOT EXISTS TB_CARGO (
  codigo LONG AUTO_INCREMENT  PRIMARY KEY,
  descricao VARCHAR(250) NOT NULL,
  cod_departamento LONG NOT NULL,
  FOREIGN KEY (cod_departamento) REFERENCES TB_DEPARTAMENTO (codigo) ON DELETE CASCADE
);
  
 /*

REGIAO

*/

CREATE TABLE IF NOT EXISTS TB_REGIAO (
  codigo LONG AUTO_INCREMENT  PRIMARY KEY,
  descricao VARCHAR(250) NOT NULL
);

  
 /*

ESTADO

*/

 
CREATE TABLE IF NOT EXISTS TB_ESTADO (
  codigo LONG AUTO_INCREMENT  PRIMARY KEY,
  descricao VARCHAR(250) NOT NULL,
  uf VARCHAR(2) NOT NULL,
  cod_regiao LONG NOT NULL,
  FOREIGN KEY (cod_regiao) REFERENCES TB_REGIAO (codigo) ON DELETE CASCADE
);


  
 /*

CIDADE

*/

 
CREATE TABLE IF NOT EXISTS TB_CIDADE (
  codigo LONG AUTO_INCREMENT  PRIMARY KEY,
  descricao VARCHAR(250) NOT NULL,
  cod_estado LONG NOT NULL,
  FOREIGN KEY (cod_estado) REFERENCES TB_ESTADO (codigo) ON DELETE CASCADE
);

 
 /*

FUNCIONARIO

*/

CREATE TABLE IF NOT EXISTS TB_FUNCIONARIO (
  matricula LONG AUTO_INCREMENT  PRIMARY KEY,
  nome VARCHAR(250) NOT NULL,
  email  VARCHAR(250) NOT NULL,
  foto  VARCHAR(250) NOT NULL,
  cod_cargo LONG NOT NULL,
  FOREIGN KEY (cod_cargo) REFERENCES TB_CIDADE (codigo) ON DELETE CASCADE
 );

/*

ENDERECO

*/

CREATE TABLE IF NOT EXISTS TB_ENDERECO (
  codigo LONG AUTO_INCREMENT  PRIMARY KEY,
  descricao VARCHAR(250) NOT NULL,
  logradouro  VARCHAR(250) NOT NULL,
  numero LONG NOT NULL,
  cep VARCHAR(8) NOT NULL,
  cod_tipo_end LONG NOT NULL,
  cod_tipo_logradouro LONG NOT NULL,
  cod_cidade LONG NOT NULL,
  cod_funcionario LONG NOT NULL,
  FOREIGN KEY (cod_tipo_end) REFERENCES TB_TIPO_ENDERECO (codigo) ON DELETE CASCADE,
  FOREIGN KEY (cod_tipo_logradouro) REFERENCES TB_TIPO_LOGRADOURO (codigo) ON DELETE CASCADE,
  FOREIGN KEY (cod_cidade) REFERENCES TB_CIDADE (codigo) ON DELETE CASCADE,
  FOREIGN KEY (cod_funcionario) REFERENCES TB_FUNCIONARIO (matricula) ON DELETE CASCADE
 );

 /*

TIPO_TELEFONE

*/

CREATE TABLE IF NOT EXISTS TB_TIPO_TELEFONE (
  codigo LONG AUTO_INCREMENT  PRIMARY KEY,
  descricao VARCHAR(250) NOT NULL
 );
 
  /*

TELEFONE

*/

CREATE TABLE IF NOT EXISTS TB_TELEFONE (
  codigo LONG AUTO_INCREMENT  PRIMARY KEY,
  descricao VARCHAR(250) NOT NULL,
  numero VARCHAR(15) NOT NULL,
  ddd VARCHAR(3) NOT NULL,
  cod_tipo_telefone LONG NOT NULL,
  cod_funcionario LONG NOT NULL,
  FOREIGN KEY (cod_tipo_telefone) REFERENCES TB_TIPO_TELEFONE (codigo) ON DELETE CASCADE,
  FOREIGN KEY (cod_funcionario) REFERENCES TB_FUNCIONARIO (matricula) ON DELETE CASCADE
 );


